import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const HEX = {
  Oxblood: "#6B1C2A",
  Bone: "#E8E0D4",
  Ink: "#1A1A1A",
  Sage: "#8A9A7B",
  Sand: "#C4B49A",
  Navy: "#1C2A4A",
  Forest: "#2F4F3E",
  Clay: "#B56A4E",
  Ivory: "#F3EEE6",
  Slate: "#5C6370",
  Charcoal: "#2E2E2E",
  Camel: "#C19A6B",
};

const APPAREL = ["XS", "S", "M", "L", "XL"];
const KIDS = ["4", "6", "8", "10", "12"];
const SHOES = ["36", "37", "38", "39", "40", "41", "42", "43", "44"];
const ONE = ["OS"];

function qtyMap(keys, fill, overrides = {}) {
  return keys.map((size) => ({ size, qty: overrides[size] ?? fill }));
}

function img(slug, n) {
  return `/atelier-vale/products/${slug}-${n}.webp`;
}

function makeProduct(p, index) {
  const variants = p.colors.map((color, i) => ({
    color,
    colorHex: HEX[color],
    sizes: qtyMap(p.sizeKeys, p.oos ? 0 : p.fill ?? 8, p.oos ? {} : p.sizeOverrides?.[color] ?? {}),
    image: img(p.slug, i === 0 ? 1 : 2),
  }));
  const stockQty = variants.reduce(
    (sum, v) => sum + v.sizes.reduce((s, z) => s + z.qty, 0),
    0,
  );
  const reviews = [
    {
      author: p.reviewA.author,
      rating: p.reviewA.rating,
      body: p.reviewA.body,
      date: p.reviewA.date,
    },
    {
      author: p.reviewB.author,
      rating: p.reviewB.rating,
      body: p.reviewB.body,
      date: p.reviewB.date,
    },
  ];
  const rating =
    Math.round(
      ((reviews[0].rating + reviews[1].rating) / 2) * 10,
    ) / 10;
  return {
    id: `p-${String(index + 1).padStart(2, "0")}`,
    slug: p.slug,
    name: p.name,
    description: p.description,
    category: p.category,
    brand: p.brand,
    sku: p.sku,
    price: p.price,
    ...(p.compareAtPrice ? { compareAtPrice: p.compareAtPrice } : {}),
    image: img(p.slug, 1),
    hoverImage: img(p.slug, 2),
    images: [img(p.slug, 1), img(p.slug, 2), img(p.slug, 3), img(p.slug, 4)],
    variants,
    materials: p.materials,
    rating,
    reviewCount: 2,
    featured: Boolean(p.featured),
    published: true,
    inStock: stockQty > 0,
    stockQty,
    ...(p.badge ? { badge: p.badge } : {}),
    features: p.features,
    specifications: p.specifications,
    reviews,
    questions: [p.question],
    sizeGuide: p.sizeGuide,
    storyTitle: p.storyTitle,
    storyBody: p.storyBody,
  };
}

const apparelGuide = [
  { label: "Chest", value: "XS 32\" · S 34\" · M 36\" · L 38\" · XL 40\"" },
  { label: "Waist", value: "XS 25\" · S 27\" · M 29\" · L 31\" · XL 33\"" },
  { label: "Length", value: "Measured from high shoulder to hem" },
  { label: "Fit", value: "True to size. Size up for ease." },
];

const kidsGuide = [
  { label: "Chest", value: "4 23\" · 6 25\" · 8 27\" · 10 29\" · 12 31\"" },
  { label: "Height", value: "Age as a starting point, measure the child" },
];

const shoeGuide = [
  { label: "EU", value: "36–44" },
  { label: "Last", value: "Medium width. Half sizes, take the next full size up." },
];

const osGuide = [{ label: "Fit", value: "One size. See product notes for dimensions." }];

const products = [
  {
    slug: "harborline-oversized-graphic-sweatshirt",
    name: "Harborline Oversized Graphic Sweatshirt",
    category: "women",
    brand: "Harborline",
    sku: "AV-HL-001",
    price: 128,
    compareAtPrice: 184,
    colors: ["Bone", "Ink"],
    sizeKeys: APPAREL,
    featured: true,
    badge: "new",
    materials: ["Cotton", "SoftBlend"],
    description:
      "Cut from mid-weight loopback cotton that keeps its shape through a hundred washes. Dropped shoulder, a quiet Vale mark at the chest, rib that does not twist.",
    features: [
      "Dropped shoulder, room through the body",
      "Rib cuff and hem that recover",
      "Printed with water-based ink",
    ],
    specifications: [
      { label: "Fabric", value: "420 gsm loopback cotton" },
      { label: "Fit", value: "Oversized" },
      { label: "Weight", value: "Mid-weight" },
      { label: "Care", value: "Wash cold, hang dry" },
      { label: "Origin", value: "Cut and sewn in Portugal" },
      { label: "SKU", value: "AV-HL-001" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "A sweatshirt that sits like a jacket",
    storyBody:
      "Harborline built this for the in-between hour: studio to street. The fleece is brushed once, not twice, so it does not pill against a wool coat.",
    reviewA: {
      author: "Mara Ellison",
      rating: 5,
      body: "Weight is honest. Sleeve length is right with the cuff pushed once.",
      date: "2026-03-12",
    },
    reviewB: {
      author: "Jonah Peck",
      rating: 4,
      body: "Bought Bone. The print cracked zero after six washes.",
      date: "2026-04-02",
    },
    question: {
      question: "Does it shrink in the dryer?",
      answer: "A little if tumbled hot. We wash ours cold and hang it.",
    },
  },
  {
    slug: "northloom-cropped-tiger-tee",
    name: "Northloom Cropped Tiger Tee",
    category: "women",
    brand: "Northloom",
    sku: "AV-NL-014",
    price: 68,
    colors: ["Oxblood", "Ivory"],
    sizeKeys: APPAREL,
    fill: 10,
    badge: "hot",
    materials: ["Cotton"],
    description:
      "A cropped box tee in compact jersey. The tiger is drawn, not stock clip-art — one plate, two colours, no plastisol shine.",
    features: ["Boxy crop that hits above the hip", "Set-in sleeve", "Side seam stays true"],
    specifications: [
      { label: "Fabric", value: "180 gsm compact cotton jersey" },
      { label: "Fit", value: "Cropped box" },
      { label: "Weight", value: "Light" },
      { label: "Care", value: "Wash inside-out, cold" },
      { label: "Origin", value: "Knitted in Peru" },
      { label: "SKU", value: "AV-NL-014" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "Short on purpose",
    storyBody:
      "Northloom cuts this to sit with high-rise denim. The hem is bound, not folded, so it does not flip.",
    reviewA: {
      author: "Priya Shah",
      rating: 5,
      body: "Crop is exact. Not a belly shirt, not a tunic.",
      date: "2026-02-18",
    },
    reviewB: {
      author: "Elena Voss",
      rating: 4,
      body: "Oxblood reads deeper in person. Soft on first wear.",
      date: "2026-05-09",
    },
    question: {
      question: "Will it stretch out?",
      answer: "The jersey is compact. It recovers after a wash.",
    },
  },
  {
    slug: "dawncut-sleeveless-knit-crop",
    name: "Dawncut Sleeveless Knit Crop",
    category: "women",
    brand: "Dawncut",
    sku: "AV-DC-022",
    price: 88,
    colors: ["Sage", "Ink"],
    sizeKeys: APPAREL,
    badge: "new",
    materials: ["Cotton", "Fine wool"],
    description:
      "A fine-gauge sleeveless crop with a square neck. Cool against the skin, neat under a shirt left open.",
    features: ["Square neck that holds", "Fine rib that does not see-through", "Cropped to the waist"],
    specifications: [
      { label: "Fabric", value: "Cotton-wool fine gauge" },
      { label: "Fit", value: "Close, cropped" },
      { label: "Weight", value: "Light" },
      { label: "Care", value: "Hand wash, dry flat" },
      { label: "Origin", value: "Knitted in Scotland" },
      { label: "SKU", value: "AV-DC-022" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "Knit, not jersey",
    storyBody:
      "Dawncut used a cotton-wool mix so the crop keeps its edge in heat. No cling, no sag at the armhole.",
    reviewA: {
      author: "Hana Idris",
      rating: 5,
      body: "Armhole is modest. I wear it without a strap showing.",
      date: "2026-06-01",
    },
    reviewB: {
      author: "Claire Bennet",
      rating: 5,
      body: "Sage is the colour of dry grass, not mint.",
      date: "2026-06-20",
    },
    question: {
      question: "Is it itchy?",
      answer: "No. The wool is combed and sits inside a cotton face.",
    },
  },
  {
    slug: "silkway-drape-blouse",
    name: "Silkway Drape Blouse",
    category: "women",
    brand: "Silkway",
    sku: "AV-SW-031",
    price: 148,
    colors: ["Ivory", "Oxblood"],
    sizeKeys: APPAREL,
    materials: ["Silk-cotton"],
    description:
      "A long-sleeve blouse in silk-cotton with a set collar and a drape that falls off the shoulder seam, not the chest.",
    features: ["Covered placket", "Cuffs that button once", "Long enough to tuck clean"],
    specifications: [
      { label: "Fabric", value: "Silk-cotton voile" },
      { label: "Fit", value: "Easy, not tented" },
      { label: "Weight", value: "Light" },
      { label: "Care", value: "Dry clean or cold hand wash" },
      { label: "Origin", value: "Woven in India, sewn in Portugal" },
      { label: "SKU", value: "AV-SW-031" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "Cloth that moves, seam that stays",
    storyBody:
      "Silkway hung this on a stand for a week before they approved the hem. The drape is cut, not gathered.",
    reviewA: {
      author: "Ruth Calder",
      rating: 4,
      body: "Opaque enough for work. The cuff sits well under a knit.",
      date: "2026-01-22",
    },
    reviewB: {
      author: "Nadia Holm",
      rating: 5,
      body: "Ivory is warm, not bridal. I wear it twice a week.",
      date: "2026-03-30",
    },
    question: {
      question: "Does it wrinkle in a bag?",
      answer: "It takes a crease. Hang it; steam the front, not the drape.",
    },
  },
  {
    slug: "oak-thread-slim-denim-jacket",
    name: "Oak & Thread Slim Denim Jacket",
    category: "men",
    brand: "Oak & Thread",
    sku: "AV-OT-040",
    price: 196,
    compareAtPrice: 248,
    colors: ["Ink", "Sand"],
    sizeKeys: APPAREL,
    featured: true,
    badge: "hot",
    materials: ["Denim", "Cotton"],
    description:
      "A slim trucker in 13.5 oz denim, rinsed once. The chest pockets sit higher so a strap does not drag them.",
    features: ["Copper hardware", "Adjustable waist tabs", "Unlined, breaks in"],
    specifications: [
      { label: "Fabric", value: "13.5 oz ring denim" },
      { label: "Fit", value: "Slim through the body" },
      { label: "Weight", value: "Mid-weight" },
      { label: "Care", value: "Wash cold, inside-out, rare" },
      { label: "Origin", value: "Milled in Japan, sewn in California" },
      { label: "SKU", value: "AV-OT-040" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "Denim cut to last, not to shout",
    storyBody:
      "Oak & Thread rinse this once so the first year is yours, not the factory's. The collar stands without a fuse.",
    reviewA: {
      author: "Theo March",
      rating: 5,
      body: "Sleeves are long enough. I cuff once and they stay.",
      date: "2026-02-02",
    },
    reviewB: {
      author: "Samir Cole",
      rating: 4,
      body: "Slim is honest. If you layer a heavy knit, size up.",
      date: "2026-04-14",
    },
    question: {
      question: "Will the Sand fade fast?",
      answer: "It will lighten at the creases. That is the cloth working.",
    },
  },
  {
    slug: "harborline-work-shirt",
    name: "Harborline Work Shirt",
    category: "men",
    brand: "Harborline",
    sku: "AV-HL-055",
    price: 118,
    colors: ["Navy", "Bone"],
    sizeKeys: APPAREL,
    materials: ["Cotton"],
    description:
      "A two-pocket work shirt in mid-weight twill. The yoke is doubled. The collar is fused just enough to stand at noon.",
    features: ["Pencil slot in the left pocket", "Lockstitch buttons", "Shirttail that stays tucked"],
    specifications: [
      { label: "Fabric", value: "7 oz cotton twill" },
      { label: "Fit", value: "Regular" },
      { label: "Weight", value: "Mid-weight" },
      { label: "Care", value: "Wash warm, hang dry, press the collar" },
      { label: "Origin", value: "Sewn in Portugal" },
      { label: "SKU", value: "AV-HL-055" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "A shirt that takes a belt",
    storyBody:
      "Harborline cut this for people who lean on tables. The pocket bags are deep. The side seams are felled.",
    reviewA: {
      author: "Owen Grant",
      rating: 5,
      body: "Navy hides ink. I wear it in the studio five days.",
      date: "2026-01-08",
    },
    reviewB: {
      author: "Luis Ortega",
      rating: 4,
      body: "True to size. Shoulders sit where they should.",
      date: "2026-05-19",
    },
    question: {
      question: "Can I put it in the dryer?",
      answer: "You can. It will soften and lose a little length. We hang ours.",
    },
  },
  {
    slug: "crispform-tailored-trouser",
    name: "Crispform Tailored Trouser",
    category: "men",
    brand: "Crispform",
    sku: "AV-CF-061",
    price: 168,
    colors: ["Charcoal", "Sand"],
    sizeKeys: APPAREL,
    featured: true,
    materials: ["Fine wool", "SoftBlend"],
    description:
      "A flat-front trouser with a clean break and a hidden side adjuster. The cloth holds a crease through a damp commute.",
    features: ["Hidden side tabs", "Unfinished hem, 36 inch inseam to start", "French bearer"],
    specifications: [
      { label: "Fabric", value: "Wool-blend suiting, 260 gsm" },
      { label: "Fit", value: "Tapered, mid rise" },
      { label: "Weight", value: "Mid-weight" },
      { label: "Care", value: "Dry clean. Steam the crease." },
      { label: "Origin", value: "Cut in Brooklyn" },
      { label: "SKU", value: "AV-CF-061" },
    ],
    sizeGuide: [
      { label: "Waist", value: "XS 28\" · S 30\" · M 32\" · L 34\" · XL 36\"" },
      { label: "Rise", value: "11.5\" front on size M" },
      { label: "Hem", value: "Unfinished. Take to a tailor." },
    ],
    storyTitle: "Trousers that stand when you sit",
    storyBody:
      "Crispform fused the waist, not the whole leg. The knee still bends. The pocket stays shut without a welt shout.",
    reviewA: {
      author: "Ben Adler",
      rating: 5,
      body: "Charcoal is a true grey, not blue. Hemmed once, done.",
      date: "2026-03-03",
    },
    reviewB: {
      author: "Chris Yoon",
      rating: 4,
      body: "Rise is modern, not low. Belt optional because of the tabs.",
      date: "2026-04-27",
    },
    question: {
      question: "Do they bag at the knee?",
      answer: "Not if you hang them. The blend springs back overnight.",
    },
  },
  {
    slug: "tidewear-linen-camp-shirt",
    name: "Tidewear Linen Camp Shirt",
    category: "men",
    brand: "Tidewear",
    sku: "AV-TW-070",
    price: 98,
    colors: ["Sage", "Ivory"],
    sizeKeys: APPAREL,
    materials: ["Linen"],
    description:
      "A camp collar in garment-washed linen. The hem is straight. Wear it open over a tank or closed with one button skipped.",
    features: ["Camp collar, no fuse", "Single chest pocket", "Washed so the first wrinkle is already there"],
    specifications: [
      { label: "Fabric", value: "Washed linen" },
      { label: "Fit", value: "Relaxed" },
      { label: "Weight", value: "Light" },
      { label: "Care", value: "Wash cold, hang, do not chase every crease" },
      { label: "Origin", value: "Woven in Lithuania" },
      { label: "SKU", value: "AV-TW-070" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "Linen that already knows you",
    storyBody:
      "Tidewear washes this in enzyme so you do not spend a year softening it. The collar rolls, it does not spike.",
    reviewA: {
      author: "Marco Bell",
      rating: 5,
      body: "Sage with sand trousers. That is the whole summer.",
      date: "2026-05-02",
    },
    reviewB: {
      author: "Ivy Chen",
      rating: 4,
      body: "Bought it for someone else. Kept it. Sleeve is generous.",
      date: "2026-06-11",
    },
    question: {
      question: "Is it see-through?",
      answer: "Ivory is a little. Wear it open, or over a tank. Sage is safer.",
    },
  },
  {
    slug: "tidewear-kids-fleece-hoodie",
    name: "Tidewear Kids Fleece Hoodie",
    category: "kids",
    brand: "Tidewear",
    sku: "AV-TW-081",
    price: 64,
    colors: ["Navy", "Bone"],
    sizeKeys: KIDS,
    fill: 7,
    materials: ["Cotton", "SoftBlend"],
    description:
      "A kids' hoodie in brushed fleece with a lined hood and a kangaroo pocket deep enough for a stone collection.",
    features: ["Lined hood", "Rib that survives the dryer", "No dangling extra cords"],
    specifications: [
      { label: "Fabric", value: "Brushed cotton fleece" },
      { label: "Fit", value: "Regular kids" },
      { label: "Weight", value: "Mid-weight" },
      { label: "Care", value: "Wash warm, tumble low" },
      { label: "Origin", value: "Sewn in Portugal" },
      { label: "SKU", value: "AV-TW-081" },
    ],
    sizeGuide: kidsGuide,
    storyTitle: "Built for the playground and the car seat",
    storyBody:
      "Tidewear skipped the metal eyelets. The pocket is bartacked. The fleece does not pill on a backpack.",
    reviewA: {
      author: "Keira Holt",
      rating: 5,
      body: "Size 8 is true. Hood stays up in wind.",
      date: "2026-02-14",
    },
    reviewB: {
      author: "Dan Park",
      rating: 4,
      body: "Bone hid less mud than I hoped. Still the better colour.",
      date: "2026-03-21",
    },
    question: {
      question: "Is the hood lined?",
      answer: "Yes, in the same jersey as the body. No scratch.",
    },
  },
  {
    slug: "northloom-mini-graphic-tee",
    name: "Northloom Mini Graphic Tee",
    category: "kids",
    brand: "Northloom",
    sku: "AV-NL-082",
    price: 48,
    colors: ["Oxblood", "Ink"],
    sizeKeys: KIDS,
    fill: 9,
    materials: ["Cotton"],
    description:
      "A kids' tee in the same compact jersey as the grown one. Short sleeve, easy neck, a small Vale stamp at the hem.",
    features: ["Bound neck that does not bag", "Straight hem", "Print that survives bleach-free wash"],
    specifications: [
      { label: "Fabric", value: "160 gsm cotton jersey" },
      { label: "Fit", value: "Regular kids" },
      { label: "Weight", value: "Light" },
      { label: "Care", value: "Wash cold, tumble low" },
      { label: "Origin", value: "Knitted in Peru" },
      { label: "SKU", value: "AV-NL-082" },
    ],
    sizeGuide: kidsGuide,
    storyTitle: "The same cloth, a shorter story",
    storyBody:
      "Northloom refused a cheaper kids' jersey. This is the adult mill, smaller pattern.",
    reviewA: {
      author: "Sofia Rios",
      rating: 5,
      body: "Neck is not tight. That is the whole review.",
      date: "2026-04-04",
    },
    reviewB: {
      author: "Paul Singh",
      rating: 4,
      body: "Ink hid lunch. Bought two.",
      date: "2026-05-16",
    },
    question: {
      question: "Does it run small?",
      answer: "No. If they are between sizes, take the larger for a year.",
    },
  },
  {
    slug: "oak-thread-kids-denim",
    name: "Oak & Thread Kids Denim",
    category: "kids",
    brand: "Oak & Thread",
    sku: "AV-OT-083",
    price: 78,
    colors: ["Ink", "Sand"],
    sizeKeys: KIDS,
    fill: 6,
    materials: ["Denim", "Cotton"],
    description:
      "Kids' jeans in a softer 11 oz denim with an adjustable elastic inside the waist. Knees are doubled on the inside.",
    features: ["Hidden waist elastic", "Reinforced knee", "Straight leg"],
    specifications: [
      { label: "Fabric", value: "11 oz denim" },
      { label: "Fit", value: "Straight" },
      { label: "Weight", value: "Mid-weight" },
      { label: "Care", value: "Wash cold, inside-out" },
      { label: "Origin", value: "Sewn in California" },
      { label: "SKU", value: "AV-OT-083" },
    ],
    sizeGuide: kidsGuide,
    storyTitle: "Jeans that survive the slide",
    storyBody:
      "Oak & Thread put a second cloth behind the knee. The rivets are dull, not sharp on a car seat.",
    reviewA: {
      author: "Nina Brooks",
      rating: 5,
      body: "Elastic actually works. We got a season, not a month.",
      date: "2026-01-19",
    },
    reviewB: {
      author: "Greg Hale",
      rating: 4,
      body: "Sand shows dust. Ink is the school pair.",
      date: "2026-02-28",
    },
    question: {
      question: "Can they kneel without blowing out?",
      answer: "That is why the knee is doubled. Still not armour.",
    },
  },
  {
    slug: "velvet-lane-curve-knit-dress",
    name: "Velvet Lane Curve Knit Dress",
    category: "curve",
    brand: "Velvet Lane",
    sku: "AV-VL-090",
    price: 176,
    colors: ["Ink", "Oxblood"],
    sizeKeys: APPAREL,
    fill: 5,
    featured: true,
    materials: ["Fine wool", "SoftBlend"],
    description:
      "A long-sleeve knit dress graded on a curve block. The waist is suggested, not cinched. The skirt falls to mid-calf.",
    features: ["Curve block from size XS up", "Long sleeve with a clean cuff", "Midi that clears a boot"],
    specifications: [
      { label: "Fabric", value: "Fine wool-blend knit" },
      { label: "Fit", value: "Curve, midi" },
      { label: "Weight", value: "Mid-weight" },
      { label: "Care", value: "Hand wash, dry flat" },
      { label: "Origin", value: "Knitted in Italy" },
      { label: "SKU", value: "AV-VL-090" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "A dress that starts with the hip",
    storyBody:
      "Velvet Lane graded this from a real curve fit model, not a scaled-up sample. The sleeve does not drag.",
    reviewA: {
      author: "Alicia Grant",
      rating: 5,
      body: "Hip is allowed to exist. That is rare in a knit dress.",
      date: "2026-03-08",
    },
    reviewB: {
      author: "Dina Moreau",
      rating: 5,
      body: "Oxblood is winter. I wear a belt only if I want to.",
      date: "2026-04-18",
    },
    question: {
      question: "Is it clingy?",
      answer: "It skims. A slip is optional, not required.",
    },
  },
  {
    slug: "harborline-curve-wide-trouser",
    name: "Harborline Curve Wide Trouser",
    category: "curve",
    brand: "Harborline",
    sku: "AV-HL-091",
    price: 138,
    colors: ["Bone", "Navy"],
    sizeKeys: APPAREL,
    fill: 6,
    materials: ["Cotton", "SoftBlend"],
    description:
      "A wide-leg trouser on a curve rise. Soft twill, front pleat that opens when you walk, pocket bags that do not gap.",
    features: ["Higher back rise", "Deep side pockets", "Full leg, cropped to ankle"],
    specifications: [
      { label: "Fabric", value: "Cotton twill with a little give" },
      { label: "Fit", value: "Wide, curve rise" },
      { label: "Weight", value: "Mid-weight" },
      { label: "Care", value: "Wash cold, hang, press the pleat" },
      { label: "Origin", value: "Sewn in Portugal" },
      { label: "SKU", value: "AV-HL-091" },
    ],
    sizeGuide: [
      { label: "Waist", value: "Sit at the true waist. Do not size down." },
      { label: "Rise", value: "12.5\" front on size M" },
      { label: "Leg", value: "Wide, cropped" },
    ],
    storyTitle: "Width with a waist",
    storyBody:
      "Harborline kept the pleat shallow so it does not add bulk. The hem is weighted. It walks.",
    reviewA: {
      author: "Lena Ortiz",
      rating: 5,
      body: "Back rise is the whole point. No gap.",
      date: "2026-05-05",
    },
    reviewB: {
      author: "June Adler",
      rating: 4,
      body: "Bone with the drape blouse. That is the uniform.",
      date: "2026-06-02",
    },
    question: {
      question: "Do I need a belt?",
      answer: "Not if you take your waist size. The pleat holds.",
    },
  },
  {
    slug: "silkway-column-dress",
    name: "Silkway Column Dress",
    category: "dresses",
    brand: "Silkway",
    sku: "AV-SW-101",
    price: 220,
    compareAtPrice: 280,
    colors: ["Ink", "Ivory"],
    sizeKeys: APPAREL,
    featured: true,
    badge: "sale",
    materials: ["Silk-cotton"],
    description:
      "A column dress with a boat neck and a seam that runs from underarm to hem. Evening without sequins.",
    features: ["Boat neck", "Invisible side zip", "Ankle length, slit at the back"],
    specifications: [
      { label: "Fabric", value: "Silk-cotton satin" },
      { label: "Fit", value: "Column" },
      { label: "Weight", value: "Light" },
      { label: "Care", value: "Dry clean" },
      { label: "Origin", value: "Sewn in Portugal" },
      { label: "SKU", value: "AV-SW-101" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "A line, not a costume",
    storyBody:
      "Silkway hung this on a live model for an hour. If the hem kicked, they recut. It does not kick.",
    reviewA: {
      author: "Helen Cho",
      rating: 5,
      body: "Ink for a winter wedding. Nobody asked who I was wearing. Good.",
      date: "2026-01-11",
    },
    reviewB: {
      author: "Amelia Frost",
      rating: 4,
      body: "Ivory needs a slip in sun. Worth it.",
      date: "2026-03-17",
    },
    question: {
      question: "Can I sit in it?",
      answer: "Yes. The back slit is there for that, not for show.",
    },
  },
  {
    slug: "dawncut-bias-slip-dress",
    name: "Dawncut Bias Slip Dress",
    category: "dresses",
    brand: "Dawncut",
    sku: "AV-DC-102",
    price: 188,
    colors: ["Sage", "Clay"],
    sizeKeys: APPAREL,
    materials: ["Silk-cotton"],
    description:
      "A bias slip with adjustable straps and a V that stops where it should. Wear it alone or under the overcoat.",
    features: ["Bias cut", "Adjustable straps", "Midi"],
    specifications: [
      { label: "Fabric", value: "Silk-cotton charmeuse" },
      { label: "Fit", value: "Bias, midi" },
      { label: "Weight", value: "Light" },
      { label: "Care", value: "Hand wash cold, dry flat" },
      { label: "Origin", value: "Cut in New York" },
      { label: "SKU", value: "AV-DC-102" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "Bias is a behaviour, not a trim",
    storyBody:
      "Dawncut rests this cloth for a day after cutting so the hem does not grow on you a week later.",
    reviewA: {
      author: "Yara Nasser",
      rating: 5,
      body: "Clay is the colour of brick in late sun. Straps do not slip.",
      date: "2026-04-09",
    },
    reviewB: {
      author: "Mina Wells",
      rating: 4,
      body: "Size for the bust. The hip will follow on the bias.",
      date: "2026-05-22",
    },
    question: {
      question: "Do I need a special bra?",
      answer: "A slim strap or none. The V is not a plunge.",
    },
  },
  {
    slug: "velvet-lane-knit-midi-dress",
    name: "Velvet Lane Knit Midi Dress",
    category: "dresses",
    brand: "Velvet Lane",
    sku: "AV-VL-103",
    price: 164,
    colors: ["Forest", "Bone"],
    sizeKeys: APPAREL,
    materials: ["Cotton", "Fine wool"],
    description:
      "A short-sleeve knit midi with a round neck and a skirt that sits, then falls. Day dress. Train dress. Both.",
    features: ["Short sleeve", "Midi skirt with a little A", "Neck that does not gape"],
    specifications: [
      { label: "Fabric", value: "Cotton-wool compact knit" },
      { label: "Fit", value: "Easy midi" },
      { label: "Weight", value: "Mid-weight" },
      { label: "Care", value: "Hand wash, dry flat" },
      { label: "Origin", value: "Knitted in Italy" },
      { label: "SKU", value: "AV-VL-103" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "The dress you forget you put on",
    storyBody:
      "Velvet Lane wanted a knit you could sit in for three hours. The skirt has a panel so it does not ride.",
    reviewA: {
      author: "Cora James",
      rating: 5,
      body: "Forest with the leather belt. That is autumn.",
      date: "2026-02-07",
    },
    reviewB: {
      author: "Bea Lind",
      rating: 4,
      body: "Bone shows less than I feared. I still prefer Forest.",
      date: "2026-03-29",
    },
    question: {
      question: "Can I layer a shirt under it?",
      answer: "A thin one. The neck is round, not wide.",
    },
  },
  {
    slug: "velvet-lane-cozy-pullover",
    name: "Velvet Lane Cozy Pullover",
    category: "fall-winter",
    brand: "Velvet Lane",
    sku: "AV-VL-110",
    price: 142,
    compareAtPrice: 198,
    colors: ["Camel", "Ink"],
    sizeKeys: APPAREL,
    featured: true,
    badge: "sale",
    materials: ["Fine wool", "SoftBlend"],
    description:
      "A crew pullover in a lofty yarn that is warm without the itch. Rib at the neck that does not flare in a month.",
    features: ["Crew that sits on the collarbone", "Lofty but not sloppy", "Cuffs you can push"],
    specifications: [
      { label: "Fabric", value: "Lambswool blend" },
      { label: "Fit", value: "Relaxed" },
      { label: "Weight", value: "Heavy" },
      { label: "Care", value: "Hand wash, dry flat, never hang wet" },
      { label: "Origin", value: "Knitted in Scotland" },
      { label: "SKU", value: "AV-VL-110" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "Warmth you can wear indoors",
    storyBody:
      "Velvet Lane spun this with a hollow yarn so it traps air. You take the coat off and you are still dressed.",
    reviewA: {
      author: "Peter Lang",
      rating: 5,
      body: "Camel with the denim jacket. No itch at the neck.",
      date: "2026-01-04",
    },
    reviewB: {
      author: "Nora Quinn",
      rating: 4,
      body: "True oversized. I took my usual size and it is right.",
      date: "2026-02-11",
    },
    question: {
      question: "Will it pill under a bag?",
      answer: "A little at the side. A comb takes it off. That is wool.",
    },
  },
  {
    slug: "oak-thread-wool-overcoat",
    name: "Oak & Thread Wool Overcoat",
    category: "fall-winter",
    brand: "Oak & Thread",
    sku: "AV-OT-111",
    price: 280,
    colors: ["Charcoal", "Camel"],
    sizeKeys: APPAREL,
    fill: 4,
    featured: true,
    materials: ["Fine wool"],
    description:
      "A single-breasted overcoat in boiled wool. Notch lapel, two flap pockets, a vent that actually vents.",
    features: ["Boiled wool, unlined at the back", "Notch lapel", "Knee length"],
    specifications: [
      { label: "Fabric", value: "Boiled wool, 520 gsm" },
      { label: "Fit", value: "Straight, room for a knit" },
      { label: "Weight", value: "Heavy" },
      { label: "Care", value: "Brush. Dry clean once a season." },
      { label: "Origin", value: "Cut in Brooklyn" },
      { label: "SKU", value: "AV-OT-111" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "A coat with a job",
    storyBody:
      "Oak & Thread boiled the wool so rain beads. The back is unlined so you do not steam on the train.",
    reviewA: {
      author: "Arthur Vale",
      rating: 5,
      body: "Charcoal with everything. Buttons are horn, not plastic.",
      date: "2026-01-15",
    },
    reviewB: {
      author: "Simone Reed",
      rating: 5,
      body: "I wear a pullover under it. Sleeve length still covers the knit.",
      date: "2026-02-20",
    },
    question: {
      question: "Is it waterproof?",
      answer: "It sheds light rain. It is wool, not a shell.",
    },
  },
  {
    slug: "harborline-merino-mockneck",
    name: "Harborline Merino Mockneck",
    category: "fall-winter",
    brand: "Harborline",
    sku: "AV-HL-112",
    price: 156,
    colors: ["Ink", "Forest"],
    sizeKeys: APPAREL,
    fill: 7,
    sizeOverrides: { Ink: { M: 3, L: 2 } },
    materials: ["Fine wool"],
    description:
      "A fine merino mockneck that layers under the overcoat and does not bulk at the collar. Thin, warm, finished.",
    features: ["Mock neck, not a funnel", "Fine gauge", "Long enough to stay tucked"],
    specifications: [
      { label: "Fabric", value: "18.5 micron merino" },
      { label: "Fit", value: "Close" },
      { label: "Weight", value: "Light" },
      { label: "Care", value: "Hand wash, dry flat" },
      { label: "Origin", value: "Knitted in New Zealand yarn, Scotland" },
      { label: "SKU", value: "AV-HL-112" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "The layer you forget",
    storyBody:
      "Harborline wanted merino that does not smell after a day and does not itch at the jaw. This is that knit.",
    reviewA: {
      author: "Will Hart",
      rating: 5,
      body: "Under the work shirt in January. No bulk at the button.",
      date: "2026-01-28",
    },
    reviewB: {
      author: "Eva Strom",
      rating: 4,
      body: "Forest is dark. Not pine, not black. Good.",
      date: "2026-03-06",
    },
    question: {
      question: "Does merino itch?",
      answer: "This micron does not, unless you are very sensitive at the neck.",
    },
  },
  {
    slug: "crispform-leather-derby",
    name: "Crispform Leather Derby",
    category: "shoes",
    brand: "Crispform",
    sku: "AV-CF-120",
    price: 248,
    colors: ["Ink", "Camel"],
    sizeKeys: SHOES,
    fill: 3,
    materials: ["Leather"],
    description:
      "A five-eye derby on a modest last. Calf leather, stacked heel, a sole you can resole.",
    features: ["Goodyear-ready construction", "Leather insole", "Stacked leather heel"],
    specifications: [
      { label: "Fabric", value: "Calf leather upper" },
      { label: "Fit", value: "Medium last" },
      { label: "Weight", value: "Solid" },
      { label: "Care", value: "Brush, cream, trees" },
      { label: "Origin", value: "Made in Northampton" },
      { label: "SKU", value: "AV-CF-120" },
    ],
    sizeGuide: shoeGuide,
    storyTitle: "A shoe that can be repaired",
    storyBody:
      "Crispform refused a glued fashion sole. Take these to a cobbler in five years. That is the point.",
    reviewA: {
      author: "James Whit",
      rating: 5,
      body: "True to EU size. Broke in over a week, not a month.",
      date: "2026-02-09",
    },
    reviewB: {
      author: "Omar Diaz",
      rating: 4,
      body: "Camel scuffs visibly. I like that. Ink is the office pair.",
      date: "2026-04-01",
    },
    question: {
      question: "Are they comfortable on day one?",
      answer: "Wearable. Not slipper-soft. Use trees. Walk.",
    },
  },
  {
    slug: "tidewear-canvas-court-shoe",
    name: "Tidewear Canvas Court Shoe",
    category: "shoes",
    brand: "Tidewear",
    sku: "AV-TW-121",
    price: 118,
    colors: ["Bone", "Navy"],
    sizeKeys: SHOES,
    fill: 8,
    materials: ["Canvas", "Leather"],
    description:
      "A low court shoe in washed canvas with a gum sole and a leather lining at the heel. Summer, errand, train.",
    features: ["Gum cupsole", "Leather heel lining", "Removable insole"],
    specifications: [
      { label: "Fabric", value: "Washed canvas, rubber cupsole" },
      { label: "Fit", value: "Regular" },
      { label: "Weight", value: "Light" },
      { label: "Care", value: "Brush dirt. Spot clean." },
      { label: "Origin", value: "Made in Vietnam" },
      { label: "SKU", value: "AV-TW-121" },
    ],
    sizeGuide: shoeGuide,
    storyTitle: "A court shoe that is not a logo",
    storyBody:
      "Tidewear kept the foxing clean and the branding off the side. The gum sole is the only shine.",
    reviewA: {
      author: "Rae Kim",
      rating: 5,
      body: "Bone with linen. I own two because I wrecked the first pair walking.",
      date: "2026-05-08",
    },
    reviewB: {
      author: "Tom Ellis",
      rating: 4,
      body: "Take your usual EU size. Wide foot, maybe 43 instead of 42.",
      date: "2026-06-14",
    },
    question: {
      question: "Can I throw them in the wash?",
      answer: "We do not. The gum sole lasts longer if you brush them.",
    },
  },
  {
    slug: "silkway-soft-tote",
    name: "Silkway Soft Tote",
    category: "bags",
    brand: "Silkway",
    sku: "AV-SW-130",
    price: 168,
    colors: ["Sand", "Ink"],
    sizeKeys: ONE,
    fill: 12,
    featured: true,
    materials: ["Leather"],
    description:
      "An unlined leather tote that slumps the right amount. Two handles, one inside pocket, room for a book and a sweater.",
    features: ["Unlined vegetable-tanned leather", "Inside slip pocket", "Handles that sit on the shoulder"],
    specifications: [
      { label: "Fabric", value: "Vegetable-tanned leather" },
      { label: "Fit", value: "Holds a 13\" laptop sleeved" },
      { label: "Weight", value: "Light for leather" },
      { label: "Care", value: "Wipe. Condition twice a year." },
      { label: "Origin", value: "Made in Florence" },
      { label: "SKU", value: "AV-SW-130" },
    ],
    sizeGuide: [
      { label: "Size", value: "38 × 30 × 12 cm" },
      { label: "Handle drop", value: "24 cm" },
    ],
    storyTitle: "A bag that gets better dirty",
    storyBody:
      "Silkway leaves this leather unfinished on purpose. The first rain mark is the start of the bag, not the end.",
    reviewA: {
      author: "Greta Holm",
      rating: 5,
      body: "Sand took a month to look like mine. That was the pleasure.",
      date: "2026-03-11",
    },
    reviewB: {
      author: "Ian Brooks",
      rating: 4,
      body: "No zip. I knew that. Still wish for a snap on crowded trains.",
      date: "2026-04-23",
    },
    question: {
      question: "Is there a zip?",
      answer: "No. A snap under the handle is as far as we go in v1.",
    },
  },
  {
    slug: "northloom-compact-crossbody",
    name: "Northloom Compact Crossbody",
    category: "bags",
    brand: "Northloom",
    sku: "AV-NL-131",
    price: 96,
    colors: ["Oxblood", "Ink"],
    sizeKeys: ONE,
    fill: 10,
    materials: ["Leather"],
    description:
      "A small crossbody for phone, keys, a card case. Adjustable strap, a flap that closes with a hidden magnet.",
    features: ["Hidden magnet flap", "Adjustable strap", "Back slip for a transit card"],
    specifications: [
      { label: "Fabric", value: "Chrome-free leather" },
      { label: "Fit", value: "Phone plus keys" },
      { label: "Weight", value: "Light" },
      { label: "Care", value: "Wipe. Keep the magnet away from hotel keys." },
      { label: "Origin", value: "Made in Portugal" },
      { label: "SKU", value: "AV-NL-131" },
    ],
    sizeGuide: [{ label: "Size", value: "18 × 12 × 4 cm" }],
    storyTitle: "Small on purpose",
    storyBody:
      "Northloom built this for people who refuse a backpack on a dinner walk. The strap does not twist.",
    reviewA: {
      author: "Faye Okonkwo",
      rating: 5,
      body: "Oxblood with the tiger tee. Magnet is strong enough.",
      date: "2026-05-12",
    },
    reviewB: {
      author: "Liam Dunn",
      rating: 4,
      body: "Fits a large phone. Barely. That is the design.",
      date: "2026-06-03",
    },
    question: {
      question: "Will it hold a bottle of water?",
      answer: "No. That is the tote.",
    },
  },
  {
    slug: "dawncut-wool-scarf",
    name: "Dawncut Wool Scarf",
    category: "accessories",
    brand: "Dawncut",
    sku: "AV-DC-140",
    price: 58,
    colors: ["Sage", "Camel"],
    sizeKeys: ONE,
    fill: 14,
    materials: ["Fine wool"],
    description:
      "A plain-weave merino scarf with a short fringe. Light enough for a coat collar, warm enough for a ferry.",
    features: ["Plain weave", "Short fringe", "Long enough to loop once"],
    specifications: [
      { label: "Fabric", value: "Merino plain weave" },
      { label: "Fit", value: "180 × 30 cm" },
      { label: "Weight", value: "Light" },
      { label: "Care", value: "Hand wash, dry flat" },
      { label: "Origin", value: "Woven in Ireland" },
      { label: "SKU", value: "AV-DC-140" },
    ],
    sizeGuide: osGuide,
    storyTitle: "A scarf that does not shout plaid",
    storyBody:
      "Dawncut kept the edges clean and the colour quiet. It is a layer, not a statement.",
    reviewA: {
      author: "Iris Patel",
      rating: 5,
      body: "Sage with the overcoat. No itch at the mouth.",
      date: "2026-01-09",
    },
    reviewB: {
      author: "Cole Martin",
      rating: 4,
      body: "Camel sheds a little at first. Then it stops.",
      date: "2026-02-16",
    },
    question: {
      question: "Is it long enough to loop twice?",
      answer: "Once with a tail. Twice if you like it short.",
    },
  },
  {
    slug: "crispform-leather-belt",
    name: "Crispform Leather Belt",
    category: "accessories",
    brand: "Crispform",
    sku: "AV-CF-141",
    price: 72,
    colors: ["Ink", "Camel"],
    sizeKeys: ["80", "85", "90", "95", "100"],
    fill: 6,
    materials: ["Leather"],
    description:
      "A 30 mm leather belt with a brushed buckle and an unfinished edge that will darken. Cut extra, punch later.",
    features: ["30 mm strap", "Brushed buckle", "Two extra holes"],
    specifications: [
      { label: "Fabric", value: "Vegetable-tanned leather" },
      { label: "Fit", value: "Size is waist in cm" },
      { label: "Weight", value: "Solid" },
      { label: "Care", value: "Wipe. Condition the back." },
      { label: "Origin", value: "Made in Florence" },
      { label: "SKU", value: "AV-CF-141" },
    ],
    sizeGuide: [
      { label: "Size", value: "Order your waist in centimetres" },
      { label: "Width", value: "30 mm" },
    ],
    storyTitle: "A belt that matches the derby, not the trend",
    storyBody:
      "Crispform cut this from the same tannery as the bag workshop. The buckle is quiet on purpose.",
    reviewA: {
      author: "Neil Capra",
      rating: 5,
      body: "90 is true for a 32 waist trouser. Edge is already ageing well.",
      date: "2026-03-14",
    },
    reviewB: {
      author: "Hugo Berg",
      rating: 4,
      body: "Camel with sand trousers. Ink with everything else.",
      date: "2026-04-08",
    },
    question: {
      question: "Can I punch more holes?",
      answer: "Yes. There is leather past the last hole.",
    },
  },
  {
    slug: "oak-thread-rib-beanie",
    name: "Oak & Thread Rib Beanie",
    category: "accessories",
    brand: "Oak & Thread",
    sku: "AV-OT-142",
    price: 48,
    colors: ["Ink", "Forest"],
    sizeKeys: ONE,
    fill: 16,
    materials: ["Fine wool"],
    description:
      "A rib beanie that covers the ears without a costume slouch. Merino, double cuff, no logo patch.",
    features: ["Double cuff", "Covers the ears", "No patch"],
    specifications: [
      { label: "Fabric", value: "Merino rib" },
      { label: "Fit", value: "One size" },
      { label: "Weight", value: "Light" },
      { label: "Care", value: "Hand wash, dry flat" },
      { label: "Origin", value: "Knitted in Scotland" },
      { label: "SKU", value: "AV-OT-142" },
    ],
    sizeGuide: osGuide,
    storyTitle: "A hat that stays on a bike",
    storyBody:
      "Oak & Thread knit this dense so wind does not find a hole. The cuff is the only volume.",
    reviewA: {
      author: "Sasha Klein",
      rating: 5,
      body: "Does not itch. Stays put. That is a beanie.",
      date: "2026-01-07",
    },
    reviewB: {
      author: "Ren Ito",
      rating: 4,
      body: "Forest with the mockneck. I look like a tree. Fine.",
      date: "2026-02-03",
    },
    question: {
      question: "Will it stretch out?",
      answer: "Rib recovers. Do not leave it on a chair arm for a week.",
    },
  },
  {
    slug: "tidewear-track-pant",
    name: "Tidewear Track Pant",
    category: "activewear",
    brand: "Tidewear",
    sku: "AV-TW-150",
    price: 88,
    colors: ["Ink", "Navy"],
    sizeKeys: APPAREL,
    oos: true,
    materials: ["Cotton", "SoftBlend"],
    description:
      "A tapered track pant in loopback with a drawcord that actually holds. Side stripe is stitched, not printed.",
    features: ["Tapered leg", "Zipped back pocket", "Drawcord that stays"],
    specifications: [
      { label: "Fabric", value: "Loopback cotton with a little stretch" },
      { label: "Fit", value: "Tapered" },
      { label: "Weight", value: "Mid-weight" },
      { label: "Care", value: "Wash cold, hang dry" },
      { label: "Origin", value: "Sewn in Portugal" },
      { label: "SKU", value: "AV-TW-150" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "A track pant for the shop, not the gym ad",
    storyBody:
      "Tidewear cut this to sit with a derby or a court shoe. The stripe is a seam, not a brand.",
    reviewA: {
      author: "Kyle Ames",
      rating: 4,
      body: "Waiting on restock. The last pair lasted two years.",
      date: "2026-03-01",
    },
    reviewB: {
      author: "Dana Ruiz",
      rating: 5,
      body: "Taper is right. Not skinny, not puddle.",
      date: "2025-11-12",
    },
    question: {
      question: "When are they back?",
      answer: "Leave an email on the product. We cut them in batches.",
    },
  },
  {
    slug: "northloom-studio-tank",
    name: "Northloom Studio Tank",
    category: "activewear",
    brand: "Northloom",
    sku: "AV-NL-151",
    price: 54,
    colors: ["Bone", "Sage"],
    sizeKeys: APPAREL,
    oos: true,
    materials: ["Cotton"],
    description:
      "A bound-neck tank in compact jersey. Wide enough at the armhole to move, not so wide it becomes a vest.",
    features: ["Bound neck and armhole", "Straight hem", "Long enough to stay in a waistband"],
    specifications: [
      { label: "Fabric", value: "Compact cotton jersey" },
      { label: "Fit", value: "Regular" },
      { label: "Weight", value: "Light" },
      { label: "Care", value: "Wash cold" },
      { label: "Origin", value: "Knitted in Peru" },
      { label: "SKU", value: "AV-NL-151" },
    ],
    sizeGuide: apparelGuide,
    storyTitle: "A tank with a seam that does not roll",
    storyBody:
      "Northloom bound every edge. It is a studio layer and a summer shirt, depending on the hour.",
    reviewA: {
      author: "Jules Faro",
      rating: 4,
      body: "Bone under the camp shirt. Waiting for the restock.",
      date: "2026-04-19",
    },
    reviewB: {
      author: "Sam Lee",
      rating: 5,
      body: "Armhole is the reason. Other tanks gape.",
      date: "2025-12-02",
    },
    question: {
      question: "Is it sheer?",
      answer: "Bone is a little. Sage is not.",
    },
  },
];

const categories = [
  {
    id: "women",
    name: "Women",
    slug: "women",
    description: "Cuts for work, weekend, and the hour between.",
    image: "/atelier-vale/cats/women.webp",
  },
  {
    id: "men",
    name: "Men",
    slug: "men",
    description: "Shirts, trousers, denim, and cloth that takes a beating.",
    image: "/atelier-vale/cats/men.webp",
  },
  {
    id: "kids",
    name: "Kids",
    slug: "kids",
    description: "The same mills, smaller patterns, tougher knees.",
    image: "/atelier-vale/cats/kids.webp",
  },
  {
    id: "curve",
    name: "Curve",
    slug: "curve",
    description: "Graded on a curve block, not scaled up from a sample.",
    image: "/atelier-vale/cats/curve.webp",
  },
  {
    id: "dresses",
    name: "Dresses",
    slug: "dresses",
    description: "Columns, bias slips, and knits you can sit in.",
    image: "/atelier-vale/cats/dresses.webp",
  },
  {
    id: "fall-winter",
    name: "Fall & Winter",
    slug: "fall-winter",
    description: "Wool, boiled cloth, and layers that stay sharp in rain.",
    image: "/atelier-vale/cats/fall-winter.webp",
  },
  {
    id: "shoes",
    name: "Shoes",
    slug: "shoes",
    description: "Derbies you can resole and court shoes without a logo.",
    image: "/atelier-vale/cats/shoes.webp",
  },
  {
    id: "bags",
    name: "Bags",
    slug: "bags",
    description: "Leather that is meant to mark. Totes and compact straps.",
    image: "/atelier-vale/cats/bags.webp",
  },
  {
    id: "accessories",
    name: "Accessories",
    slug: "accessories",
    description: "Scarves, belts, and a beanie that stays on a bike.",
    image: "/atelier-vale/cats/accessories.webp",
  },
  {
    id: "activewear",
    name: "Activewear",
    slug: "activewear",
    description: "Studio layers with seams that do not roll.",
    image: "/atelier-vale/cats/activewear.webp",
  },
];

const catalog = {
  categories,
  products: products.map(makeProduct),
};

mkdirSync(join(root, "data"), { recursive: true });
writeFileSync(join(root, "data/catalog.json"), JSON.stringify(catalog, null, 2) + "\n");
console.log(
  `Wrote ${catalog.products.length} products, ${catalog.categories.length} categories. OOS=${catalog.products.filter((p) => !p.inStock).length} featured=${catalog.products.filter((p) => p.featured).length}`,
);
